# Ed Wied
# March 5, 2022
# CS 361 - Final Project
# What the Bing?! Image Service


name: Copy Elastic Beanstalk configuration file to s3

# run workflow only on manual trigger
on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Copy configuration file to s3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install more-utils
      run: sudo apt-get install moreutils

    - name: update config
      env:
        ecrValue: ${{ secrets.AWS_ECR_PATH}}
      run: jq --arg ecrValue "$ecrValue"  '.Image.Name=$ecrValue' Dockerrun.aws.json > Dockerrun.aws.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Delete existing file
      run: |
        aws s3 rm s3://annawandev/what-the-bing/image-service/Dockerrun.aws.json

    - name: Copy new version of configuration file
      run: |
        aws s3 cp ./aws/Dockerrun.aws.json s3://annawandev/what-the-bing/image-service/Dockerrun.aws.json
