# Ed Wied
# March 6, 2022
# CS 361 - Final Project
# What the Bing?! Image Service


name: Start Elastic Beanstalk service

# run workflow only on manual trigger
on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Start Elastic Beanstalk service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create EB application version
      env:
        APP_VERSION: 1
        S3_BUCKET_CONFIG: ${{ secrets.S3_EB_BUCKET }}
      run: |
        aws elasticbeanstalk create-application-version --application-name "What the Bing Image Service" --version-label $APP_VERSION --source-bundle S3Bucket=$S3_EB_BUCKET,S3Key=Dockerrun.aws.json
